@startuml
left to right direction
actor "Gardener" as AC_G
actor "HappyPlant Friend\n(Group Member)" as AC_GM

rectangle "HappyPlant - Social Features" {
    usecase "Verify Delegated Care" as UC_VDC
    usecase "Decline Care Task" as UC_DCT
    usecase "Dispute Care Action" as UC_DCA
}

' Alternative flows
UC_DCT .u.> UC_VDC : <<extend>>
UC_DCA .d.> UC_VDC : <<extend>>

' The caretaker performs the care and the owner verifies
AC_GM --> UC_VDC
AC_G --> UC_VDC

@enduml
