@startuml
left to right direction

actor "Farmer" as AC_F

rectangle "HappyPlant - Plant Care Management" {
    usecase "Alert to Location" as UC_AL
}

' The Farmer starts the process
AC_F --> UC_AL

@enduml