@startuml
left to right direction
actor "Gardener" as AC_G

rectangle "HappyPlant - Plant Care Management" {
    usecase "Shift responsibility for a plant" as UC_ANP

}

' The actor initiates the adding operation
AC_G --> UC_ANP

@enduml