@startuml
left to right direction
actor "Gardener" as AC_G

rectangle "HappyPlant - Plant Care Management" {
    usecase "Navigate to Plant" as UC_NP
    usecase "Set Plant Location" as UC_SPL
    usecase "Show Plant Details" as UC_SPD
}

' Alternative flows
UC_SPL .u.> UC_NP : <<extend>>
UC_SPD .d.> UC_NP : <<extend>>

' The actor initiates the navigation process
AC_G --> UC_NP

@enduml
